# Generated by Django 5.2.13 on 2026-04-18 08:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='город')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='страна')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
            ],
            options={
                'verbose_name': 'аффилиация',
                'verbose_name_plural': 'аффилиации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=500, verbose_name='название статьи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='код статьи')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='подзаголовок')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('ru-en', 'Русский / Английский')], default='ru', max_length=16, verbose_name='язык публикации')),
                ('pages', models.CharField(blank=True, max_length=64, verbose_name='страницы')),
                ('doi', models.CharField(blank=True, max_length=120, verbose_name='DOI')),
                ('original_url', models.URLField(blank=True, verbose_name='URL оригинала')),
                ('abstract', models.TextField(blank=True, verbose_name='аннотация')),
                ('import_source', models.CharField(blank=True, max_length=255, verbose_name='источник импорта')),
                ('source_identifier', models.CharField(blank=True, max_length=255, verbose_name='внешний идентификатор')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-issue__year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('year', models.PositiveIntegerField(verbose_name='год')),
                ('volume', models.CharField(max_length=32, verbose_name='том')),
                ('number', models.CharField(max_length=32, verbose_name='номер')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='заголовок выпуска')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='дата публикации')),
                ('source_url', models.URLField(blank=True, verbose_name='URL выпуска')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
            ],
            options={
                'verbose_name': 'выпуск',
                'verbose_name_plural': 'выпуски',
                'ordering': ['-year', '-publication_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='полное название')),
                ('short_title', models.CharField(max_length=160, verbose_name='краткое название')),
                ('issn_print', models.CharField(blank=True, max_length=32, verbose_name='ISSN (print)')),
                ('issn_online', models.CharField(blank=True, max_length=32, verbose_name='ISSN (online)')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='издатель')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('site_url', models.URLField(blank=True, verbose_name='сайт журнала')),
                ('integration_hint', models.CharField(blank=True, max_length=255, verbose_name='вариант интеграции')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'журналы',
            },
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('file', models.FileField(blank=True, upload_to='articles/files/', verbose_name='файл')),
                ('file_kind', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('other', 'Другое')], default='pdf', max_length=16, verbose_name='тип файла')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='исходное имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME-тип')),
                ('external_url', models.URLField(blank=True, verbose_name='внешний URL')),
                ('checksum', models.CharField(blank=True, max_length=128, verbose_name='контрольная сумма')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='corpus.article', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'файл статьи',
                'verbose_name_plural': 'файлы статей',
                'ordering': ['article', 'file_kind'],
            },
        ),
        migrations.CreateModel(
            name='ArticleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title_text', models.TextField(blank=True, verbose_name='заголовок')),
                ('abstract_text', models.TextField(blank=True, verbose_name='аннотация')),
                ('keywords_text', models.TextField(blank=True, verbose_name='ключевые слова')),
                ('body_text', models.TextField(blank=True, verbose_name='основной текст')),
                ('references_text', models.TextField(blank=True, verbose_name='список литературы')),
                ('cleaned_text', models.TextField(blank=True, verbose_name='очищенный текст')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='число токенов')),
                ('lemma_count', models.PositiveIntegerField(default=0, verbose_name='число лемм')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='поисковый вектор')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='corpus.article', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'текст статьи',
                'verbose_name_plural': 'тексты статей',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('first_name', models.CharField(max_length=120, verbose_name='имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='отчество')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='код')),
                ('orcid', models.CharField(blank=True, max_length=32, verbose_name='ORCID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='электронная почта')),
                ('affiliations', models.ManyToManyField(blank=True, related_name='authors', to='corpus.affiliation', verbose_name='аффилиации')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='порядок автора')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='отображаемое имя')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_authors', to='corpus.affiliation', verbose_name='аффилиация')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_authors', to='corpus.article', verbose_name='статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='corpus.author', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'автор статьи',
                'verbose_name_plural': 'авторы статьи',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='corpus.ArticleAuthor', to='corpus.author', verbose_name='авторы'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='corpus.issue', verbose_name='выпуск'),
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='corpus.journal', verbose_name='журнал'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='corpus.journal', verbose_name='журнал'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='ключевое слово')),
                ('normalized', models.CharField(max_length=120, verbose_name='нормализованное значение')),
                ('language', models.CharField(default='ru', max_length=16, verbose_name='язык')),
            ],
            options={
                'verbose_name': 'ключевое слово',
                'verbose_name_plural': 'ключевые слова',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('normalized', 'language'), name='unique_keyword_per_language')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='articles', to='corpus.keyword', verbose_name='ключевые слова'),
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('text', models.CharField(max_length=120, verbose_name='лемма')),
                ('normalized', models.CharField(max_length=120, verbose_name='нормализованное значение')),
                ('language', models.CharField(default='ru', max_length=16, verbose_name='язык')),
                ('part_of_speech', models.CharField(blank=True, max_length=32, verbose_name='часть речи')),
            ],
            options={
                'verbose_name': 'лемма',
                'verbose_name_plural': 'леммы',
                'ordering': ['normalized'],
                'constraints': [models.UniqueConstraint(fields=('normalized', 'language', 'part_of_speech'), name='unique_lemma_per_language_pos')],
            },
        ),
        migrations.CreateModel(
            name='ArticleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('token', models.CharField(max_length=120, verbose_name='токен')),
                ('normalized', models.CharField(blank=True, max_length=120, verbose_name='нормализованная форма')),
                ('morph_tag', models.CharField(blank=True, max_length=128, verbose_name='морфологическая информация')),
                ('position', models.PositiveIntegerField(verbose_name='позиция')),
                ('sentence_index', models.PositiveIntegerField(default=0, verbose_name='номер предложения')),
                ('char_start', models.PositiveIntegerField(default=0, verbose_name='символ начала')),
                ('char_end', models.PositiveIntegerField(default=0, verbose_name='символ конца')),
                ('source_section', models.CharField(choices=[('title', 'Заголовок'), ('abstract', 'Аннотация'), ('keywords', 'Ключевые слова'), ('body', 'Основной текст'), ('references', 'Литература')], default='body', max_length=32, verbose_name='часть текста')),
                ('is_alpha', models.BooleanField(default=False, verbose_name='буквенный токен')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.article', verbose_name='статья')),
                ('article_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='corpus.articletext', verbose_name='текст статьи')),
                ('lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='corpus.lemma', verbose_name='лемма')),
            ],
            options={
                'verbose_name': 'токен статьи',
                'verbose_name_plural': 'токены статьи',
                'ordering': ['article_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('query_payload', models.JSONField(default=dict, verbose_name='параметры запроса')),
                ('last_result_count', models.PositiveIntegerField(default=0, verbose_name='последнее число результатов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сохраненный запрос',
                'verbose_name_plural': 'сохраненные запросы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSubcorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('filter_payload', models.JSONField(blank=True, default=dict, verbose_name='фильтры')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичный')),
                ('article_count', models.PositiveIntegerField(default=0, verbose_name='число статей')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='число токенов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_subcorpora', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сохраненный подкорпус',
                'verbose_name_plural': 'сохраненные подкорпуса',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSubcorpusArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('source', models.CharField(choices=[('filter', 'По фильтру'), ('manual', 'Добавлено вручную')], default='filter', max_length=16, verbose_name='источник')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcorpus_links', to='corpus.article', verbose_name='статья')),
                ('subcorpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcorpus_articles', to='corpus.savedsubcorpus', verbose_name='подкорпус')),
            ],
            options={
                'verbose_name': 'статья в подкорпусе',
                'verbose_name_plural': 'статьи в подкорпусах',
            },
        ),
        migrations.AddField(
            model_name='savedsubcorpus',
            name='articles',
            field=models.ManyToManyField(related_name='saved_subcorpora', through='corpus.SavedSubcorpusArticle', to='corpus.article', verbose_name='статьи'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('query_text', models.CharField(blank=True, max_length=255, verbose_name='строка поиска')),
                ('search_type', models.CharField(choices=[('fulltext', 'Полнотекстовый поиск'), ('lemma', 'Поиск по лемме'), ('wordform', 'Поиск по словоформе'), ('phrase', 'Поиск по фразе'), ('metadata', 'Поиск по метаданным')], max_length=16, verbose_name='тип поиска')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='фильтры')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='число результатов')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'история поиска',
                'verbose_name_plural': 'история поиска',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=140, verbose_name='код')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='corpus.journal', verbose_name='журнал')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='corpus.section', verbose_name='раздел'),
        ),
        migrations.AddIndex(
            model_name='articletext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='corpus_arti_search__9dabe4_gin'),
        ),
        migrations.AddConstraint(
            model_name='articleauthor',
            constraint=models.UniqueConstraint(fields=('article', 'author', 'order'), name='unique_author_order_per_article'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('journal', 'year', 'volume', 'number'), name='unique_issue_per_journal'),
        ),
        migrations.AddIndex(
            model_name='articletoken',
            index=models.Index(fields=['article', 'position'], name='corpus_arti_article_018f66_idx'),
        ),
        migrations.AddIndex(
            model_name='articletoken',
            index=models.Index(fields=['normalized'], name='corpus_arti_normali_93db70_idx'),
        ),
        migrations.AddIndex(
            model_name='articletoken',
            index=models.Index(fields=['source_section'], name='corpus_arti_source__360161_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsubcorpusarticle',
            constraint=models.UniqueConstraint(fields=('subcorpus', 'article'), name='unique_article_in_subcorpus'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('journal', 'slug'), name='unique_section_slug_per_journal'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['language'], name='corpus_arti_languag_dd68c3_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='corpus_arti_doi_1ba287_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='corpus_arti_slug_1f6bc4_idx'),
        ),
    ]
