# Generated by Django 5.2.14 on 2026-05-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_articlehighlight_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='geography_confidence',
            field=models.FloatField(default=0, verbose_name='уверенность геопривязки'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='geography_source',
            field=models.CharField(blank=True, max_length=64, verbose_name='источник геопривязки'),
        ),
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('display_name', models.CharField(max_length=128, verbose_name='город')),
                ('normalized_name', models.CharField(max_length=128, verbose_name='нормализованное название')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='регион')),
                ('country', models.CharField(default='Россия', max_length=128, verbose_name='страна')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('geocode_source', models.CharField(default='gazetteer', max_length=64, verbose_name='источник координат')),
                ('is_verified', models.BooleanField(default=False, verbose_name='проверено')),
                ('needs_review', models.BooleanField(default=False, verbose_name='нужна проверка')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['country', 'display_name'],
                'indexes': [models.Index(fields=['normalized_name'], name='corpus_city_normali_deff6c_idx'), models.Index(fields=['country'], name='corpus_city_country_09dde4_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'country'), name='unique_city_location_country')],
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='city_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliations', to='corpus.citylocation', verbose_name='географическая привязка'),
        ),
    ]
