# Generated by Django 5.2.13 on 2026-04-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='код')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='может управлять пользователями')),
                ('can_edit_content', models.BooleanField(default=False, verbose_name='может редактировать содержимое')),
                ('can_run_imports', models.BooleanField(default=False, verbose_name='может запускать импорт')),
                ('can_save_queries', models.BooleanField(default=False, verbose_name='может сохранять запросы')),
            ],
            options={
                'verbose_name': 'роль',
                'verbose_name_plural': 'роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('activity_type', models.CharField(choices=[('search', 'Поиск'), ('subcorpus', 'Подкорпус'), ('export', 'Экспорт'), ('import', 'Импорт'), ('login', 'Вход')], max_length=32, verbose_name='тип активности')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'действие пользователя',
                'verbose_name_plural': 'действия пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='организация')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='должность')),
                ('preferred_language', models.CharField(default='ru', max_length=16, verbose_name='предпочитаемый язык')),
                ('primary_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.role', verbose_name='основная роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
    ]
